### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by jitendravyas** [juliangruber/review#15]
A part of error

```
-> Review on port 4000
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:278:26)
    at exports.spawn (child_process.js:367:9)
    at snapshot (/usr/local/lib/node_modules/review/lib/snapshot.js:32:14)
    at /usr/local/lib/node_modules/review/lib/snapshot.js:51:14
    at callbacks (/usr/local/lib/node_modules/review/node_modules/express/lib/router/index.js:161:37)
    at param (/usr/local/lib/node_modules/review/node_modules/express/lib/router/index.js:135:11)
    at param (/usr/local/lib/node_modules/review/node_modules/express/lib/router/index.js:132:11)
    at param (/usr/local/lib/node_modules/review/node_modules/express/lib/router/index.js:132:11)
    at param (/usr/local/lib/node_modules/review/node_modules/express/lib/router/index.js:132:11)
TypeError: Bad argume
```

I'm on latest OSX.

**Comment by juliangruber** [comment]
can you share a snippet that shows how you're using review?
